### ISSUE TITLE
Replacing LTSP with our image build system

### ISSUE THREAD

**Issue by imincik** [imincik/gis-lab#308]
LTSP contains tons of features and code which we do not use at all (thin client, PnP Fat client). We use lot of LTSP client plugins overrides to achieve desired state. Also we want better integration to our system. We are investigating possibility to extract pieces we need and update them to our needs.

Analysis
=======
* isolate LTSP server and client code used for GIS.lab 
* propose new installation system more suitable for GIS.lab

Tasks
=====
* rewrite 'client-desktop' installation to Ansible
* rewrite 'client-worker' installation to Ansible
* add scripts gislab-client-chroot (activate client image chroot, mount proc, /dev/pts) and gislab-client-image (create image from current chroot state and create ramdisk, create nbi image, copy files to tftp directory). Always test if GISLAB_SUITE = 'lab' before running them
* keep concurrent login detection
* solve desktop client image rebuilding while desktop clients are connected
* keep connected users detection in 'gislab-deluser'

Paths
=====
* /opt/gislab/bin - place for gislab-client-chroot, gislab-client-image
* /opt/gislab/system/client-desktop/root - chroot
* /opt/gislab/system/client-desktop/image - image
* /opt/gislab/system/client-worker/root - files
* /opt/gislab/system/client-worker/image - image

client-worker
===========
* install whole worker configuration to /opt/gislab/system/client-worker/root using Ansible
* install 'install.sh' script

install.sh:
* create local 'gislab' superuser account with public SSH key /etc/gislab/gislab_ssh_public_key.pub
* install required packages and upgrade system
* copy whole directory tree to target system
* mount NFS from server
* restart all required services

client-desktop
============
* create chroot, install and configure software and build image
* if GISLAB_CLIENT_WORKER_ENABLED, install also QGIS Mapserver support from 'worker' files using Ansible (do not copy files directly as it is done now)
* GISLAB_CLIENT_INSTALL_PACKAGES_DEFAULT - install with recommended packages
* GISLAB_CLIENT_INSTALL_PACKAGES_GIS, GISLAB_CLIENT_INSTALL_PACKAGES - install without recommended packages
* use local SWAP partition if available

Ansible structure
=============
* files/scripts - scripts, which will be launched by Ansible 'script' module during installation
* files/static/[program_name] - program files which will be used on client when running( Ansible 'copy' module)
* files/static/bin - simple scripts, files which will be run on client when running (Ansible 'copy' module)
* templates - all configuration files (do not use 'sed' in tasks, always use configuration file in template)

LDM notes
=========
LDM isn't started like conventional services, it's run from LTSP's
screen script infrstructure. So, there's no "proper" way to stop it, but
you could use "killall ldm" or "killall ldmgtkgreeter" or kill other
running processes... It should then get restarted
automatically...

LDM definitely runs on the client, thin or fat, just not configured as a
"service" or "job".

> Vagrant said it runs from an LTSP screen script, so I guess I should
>  be able to run that script to get it going. Someone familiar with
>  that script, like where it is and the name of it...?

It's in the client's /usr/share/ltsp/screen.d/ldm, which is started by
/usr/share/ltsp/screen_session, which is started by either
/etc/init.d/ltsp-client-core or ltsp-client-core upstart job? Neither
have any stop or restart functionality... they start once and that's it.

There's not really a manual way to start it ... well, you could set
SCREEN_07=shell in lts.conf, and ". /usr/share/ltsp/screen.d/ldm" and
then once it finishes, should bring you back to the console on tty7,
where you can source it again. Pretty ugly workaround...

The menu screen script might be a slightly less ugly way to get that
behavior, as it uses a console dialog to select which session type to
run.

If you can figure out a commandline option that disables the screen
script, you could create a simple hook to run in
/usr/share/ltsp/screen-session.d/ or /usr/share/ldm/rc.d hooks to
execute your video reset on logout...

**Comment by mpastor** [comment]
### LTSP client building analyze

#### 1. */usr/sbin/ltsp-build-client* command analyze

Required packages:
* server - debootstrap squashfs-tools tftpd-hpa nbd-server
* client - nbd-client mkelfimage udhcpc


##### 1.1 basic-configuration
* setup default variables

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/000-basic-configuration


##### 1.2 purge-chroot *(cmd option)*
* clean chroot directory

-> /usr/share/ltsp/plugins/ltsp-build-client/common/01.20-rootpath


##### 1.3 copy-package-cache *(cmd option)*
* copy APT cache directory from server to chroot

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/01.1.40-copy-package-cache


##### 1.4 copy-package-lists *(cmd option)*
* copy package lists from server to chroot

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/040-copy-package-lists


##### 1.5 mount-package-cache *(cmd option)*
* mount (bind) APT cache directory from server to chroot

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/040-mount-package-cache


##### 1.6 debootstrap
* base system installation

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/01.10-debootstrap


##### 1.7 locales *(cmd option)*
* configure locales

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/01.25-locales


##### 1.8 daemon-handling
* forbid starting services in chroot during installation

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/000-daemon-handling


##### 1.9 apt-keys *(cmd option)*
* add APT keys

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/001-apt-keys


##### 1.10 debconf-seeds *(cmd option)*
* load debconf configuration

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/010-debconf-seeds

##### 1.11 etc-hostname
* zero out the hostname file, so system hostname gotten from DHCP takes priority

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/010-etc-hostname


##### 1.12 etc-hosts
* make aliase for loopback in `/etc/hosts'

-> /usr/share/ltsp/plugins/ltsp-build-client/common/010-etc-hosts


##### 1.13 etc-mtab
* divert /etc/mtab and point it to /proc/mounts

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/010-etc-mtab


##### 1.14 http-proxy *(cmd option)*
* add http proxy to chrootu

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/010-http-proxy


##### 1.15 manage-mirror *(cmd option)*
* create '/etc/apt/sources.list' - add mirrors:
 * $EARLY_MIRROR
 * $MIRROR
 * $EXTRA_MIRROR

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/010-manage-mirror


##### 1.16 mount-devpts
* mount */dev/pts*

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/010-mount-devpts


##### 1.17 mount-proc
* mount */proc*

-> /usr/share/ltsp/plugins/ltsp-build-client/common/010-mount-proc


##### 1.18 serial-console *(cmd option)*
* enable serial console

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/010-serial-console


##### 1.19 set-resolver
* copy /etc/resolv.conf from server to chroot

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/010-set-resolver


##### 1.20 updates-mirrors *(cmd option)*
* add *security* and *update* repositories

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/010-updates-mirrors


##### 1.21 var-lib-nfs
* create /var/lib/nfs in chroot

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/010-var-lib-nfs

##### 1.22 copy-sourceslist *(cmd option)*
* copy 'sources.list' to chrootu

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/015-sources-list


##### 1.23 apt-get-update
* update packages list - *apt-get update* with options

 *export APT_GET_OPTS="$APT_GET_OPTS -o Acquire::gpgv::Options::=--ignore-time-conflict"*

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/020-apt-get-update


##### 1.24 kernel-img-conf
* create configuration file for kernel installation

*$ROOT/etc/kernel-img.conf*

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/020-kernel-img-conf


##### 1.25 early-packages *(cmd option)*
* install *$EARLY_PACKAGES* packages (see also 1.1)

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/01.30-early-packages


##### 1.26 fat-client/fat-client-desktop *(cmd option)*
* install desktop meta-packages:

 - enable installation of recommended packages
 - install *FAT_CLIENT_DESKTOPS* or '*buntu-desktop' if installed on server or 'ubuntu-desktop'
 - install 'ubuntu-standard' package

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/030-fat-client

##### 1.27 apt-get-upgrade
* upgrade system - *apt-get dist-upgrade*

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/01.35-apt-get-upgrade

##### 1.28 rootpass
* lock 'root' account

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/095-rootpass


##### 1.29 no-recommends
* enable '--no-install-recommends' in chroot if fat client is not installed (see also 1.26)

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/016-no-recommends


##### 1.30 kernel-selection

* add kernel to installed packages (LATE_PACKAGES):
 - amd64: linux-image-generic if exists, else linux-image-generic-lts-trusty
 - 386: linux-image-generic-pae or linux-image-generic or linux-image-generic-lts-trusty

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/020-kernel-selection

##### 1.31 artwork
* install themes for LTSP loggin manager (ldm):

     - install `ldm-ubuntu-theme`
     - install `ldm-*-theme` for selected desktop (see also 1.26)

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/030-artwork


##### 1.32 late-packages *(cmd option)*
* install kernel packages (see 1.30) a packages added via command line option

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/030-late-packages


##### 1.33 loopback
* configure 'loopback' in '/etc/network/interfaces'

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/030-loopback


##### 1.34 update-sshkeys
* copy server SSH public keys to chroot *ssh_know_hosts* file

 `run */usr/sbin/ltsp-update-sshkeys* command`

-> /usr/share/ltsp/plugins/ltsp-build-client/common/030-update-sshkeys


##### 1.35 copy-timezone
* configure timezone

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/035-copy-timezone


##### 1.36 default-modules
* add default module *lp*

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/035-default-modules


##### 1.37 update-kernels
* copy */boot* directory from chroot to TFTP directory on server
* delete kernel from TFTP directory which doesn't have competent modules in chroot

`run */usr/sbin/ltsp-update-kernels* command`

-> /usr/share/ltsp/plugins/ltsp-build-client/common/035-update-kernels


##### 1.38 copy-package-cache *(cmd option)*
* copy APT cache from chroot to server

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/040-copy-package-cache


##### 1.39 update-sshkeys - updatne `ssh_known_hosts' again

`run */usr/sbin/ltsp-update-sshkeys* command`

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/040-update-sshkeys


##### 1.40 clean-package-cache *(cmd option)*
* clean APT cache in chroot

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/090-clean-package-cache

##### 1.41 unmount-dirs
* unmount all mounts in chroot

-> /usr/share/ltsp/plugins/ltsp-build-client/common/091-unmount-dirs


##### 1.42 rootpass *(cmd option)*
* set *root* password

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/095-rootpass


##### 1.43 update-image

* run */etc/kernel/postinst.d/ltsp-update-kernels* command in chroot:
 * configure PXE in '/boot'
 * create boot configuration file (default)
 * generate NBI (network bootable image) from newest kernel
 * create *nbi.img* symlink

* run */usr/sbin/ltsp-update-image* command on server:
 * generate client image
 * create NBD server configuration and restart service
 * create */etc/ltsp/update-kernels.conf* configuration file in chroot with kernel boot options and append *nbdroot=:ltsp_i386*
 * update kernel in chroot (/etc/kernel/postinst.d/ltsp-update-kernels)
 * copy */boot* directory from chroot to TFTP directory on server again
 * append *"nbdrootd: ALL: keepalive"* to the '/etc/hosts.allow' on server

-> /usr/share/ltsp/plugins/ltsp-build-client/Ubuntu/095-update-image


#### 2. Client booting - initrd (/init)


##### 2.1 - kernel run '/init' in initrd

##### 2.2 - 'scripts/init-premount/udhcp'

* get IP address from DHCP and configure network interface

##### 2.3 - 'scripts/local-top/nbd'

* connect NBD image - parameters are taken from */proc/cmdline* and from network variables

##### 2.4 - 'scripts/local-top/nbd_ltsp'

* set *FSTYPE variable*

##### 2.5 - mount root filesystem read-only

##### 2.6 - 'scripts/init-bottom/ltsp'
* mount root filesystem read-write
* copy files with network variables from ramdisk to new '/' filesystem

##### 2.7 - run */sbin/init-ltsp* in real '/' - system booting


#### 3. initrd configuration - *initramfs-tools*

Required files:

* /usr/share/initramfs-tools/scripts/init-premount/udhcp - 'udhcp' script with GIS.lab patch (ltsp-client-core)
* /usr/share/initramfs-tools/scripts/local-top/nbd (nbd-client)
* /usr/share/initramfs-tools/scripts/local-top/nbd_ltsp (ltsp-client-core)
* /usr/share/initramfs-tools/scripts/init-bottom/ltsp (ltsp-client-core)

* /usr/share/initramfs-tools/conf.d/ltsp (ltsp-client-core)
* /usr/share/initramfs-tools/hooks/ltsp (ltsp-client-core)
* /usr/share/initramfs-tools/hooks/udhcp (ltsp-client-core)

#### 4. Client booting - system (/sbin/init-ltsp)

##### 4.1 - /sbin/init-ltsp


##### 4.2 - clean-cache
* source files with network variables (see 2.6)

-> /usr/share/ltsp/init-ltsp.d/02-initramfs-env


##### 4.3 - initramfs-env
* setup variables according to */proc/cmdline* and save them to */var/cache/ltsp/ltsp_config*

-> /usr/share/ltsp/init-ltsp.d/03-kernel-cmdline


##### 4.4 - server
* setup *SERVER* variable and save it to */var/cache/ltsp/ltsp_config*

-> /usr/share/ltsp/init-ltsp.d/04-server


##### 4.5 - getltsconffile
* get configuration file *lts.conf* from TFTP and read variables from it

-> /usr/share/ltsp/init-ltsp.d/05-getltsconffile


##### 4.6 - hostname
* set *$HOSTNAME*, */etc/hostname* and */etc/hosts*

-> /usr/share/ltsp/init-ltsp.d/09-hostname


##### 4.7 - resolv-conf
* configure */etc/resolv.conf*

-> /usr/share/ltsp/init-ltsp.d/10-resolv-conf


##### 4.8 - modules
* load kernel modules (lts.conf)

-> /usr/share/ltsp/init-ltsp.d/20-modules


##### 4.9 - cron
* setup *cron* (lts.conf)

-> /usr/share/ltsp/init-ltsp.d/50-cron


##### 4.10 - default-display-manager
* set */etc/X11/default-display-manager* (lts.conf) or use default */usr/sbin/ldm*

-> /usr/share/ltsp/init-ltsp.d/50-default-display-manager

##### 4.11 - disable-cronjobs
* disable useless cron jobs

-> /usr/share/ltsp/init-ltsp.d/50-disable-cronjobs


##### 4.12 - fstab
* create */etc/fstab* (lts.conf)

-> /usr/share/ltsp/init-ltsp.d/50-fstab


##### 4.13 - gsettings-overrides
* disable user switching and screen locking

-> /usr/share/ltsp/init-ltsp.d/50-gsettings-overrides


##### 4.14 - interfaces
* prohibit network-manager from messing with the boot interface

-> /usr/share/ltsp/init-ltsp.d/50-interfaces


##### 4.15 - jetpipe
* configure printers (jetpipe)

-> /usr/share/ltsp/init-ltsp.d/50-jetpipe


##### 4.16 - keyboard
* configure keyboard (systeme wide)

-> /usr/share/ltsp/init-ltsp.d/50-keyboard


##### 4.17 - mtab
* delete symlink */etc/mtab* and create empty one

-> /usr/share/ltsp/init-ltsp.d/50-mtab


##### 4.18 - rcfiles
* configure */etc/rc.local* (lts.conf)

-> /usr/share/ltsp/init-ltsp.d/50-rcfiles


##### 4.19 - rm-session-services
* disable desktop autostart services *jockey-gtk* and *jockey-kde* and services defined in lts.conf

-> /usr/share/ltsp/init-ltsp.d/50-rm-session-services


##### 4.20 - rm-system-services
* disable useless system services in */etc/init**

-> /usr/share/ltsp/init-ltsp.d/50-rm-system-services


##### 4.21 - saned
* enable *saned* service (lts.conf)

-> /usr/share/ltsp/init-ltsp.d/50-saned


##### 4.22 - sendsigs
*  register pids of nbd-client and nbd-proxy so that sendsigs doesn't kill them on shutdown/reboot

-> /usr/share/ltsp/init-ltsp.d/50-sendsigs

##### 4.23 - set-time
* set timezone and NTP server (lts.conf)

-> /usr/share/ltsp/init-ltsp.d/50-set-time


##### 4.24 - swap
* setup swap (lts.conf)

-> /usr/share/ltsp/init-ltsp.d/50-swap


##### 4.25 - syslog
* configure remote logging (lts.conf)

-> /usr/share/ltsp/init-ltsp.d/50-syslog


##### 4.26 - update-motd
* clean up */etc/update-motd.d*

-> /usr/share/ltsp/init-ltsp.d/50-update-motd

##### 4.27 - run '/sbin/init'

#### 5. Client booting - upstart (/etc/init/ltsp-client-core.conf)

* screen.d/ldm script is launched during the bootup process; it
   - creates a new Xauthority file
   - creates a magic cookie and adds it with xauth
   - sets some environment variables
   - starts xinit and sources xinitrc.d scripts
   - fires up LDM

* LDM reads environment variables (some of which come from lts.conf,
   some from the screen.d script), runs ldm rc.d P* pressh and
   I* init scripts, spawns the greeter and waits for user login

* when user enters login credentials, LDM (using ssh backend) opens
   a "control socket" ssh tunnel to the server, making the ssh
   connection reusable (in the process list this is the one that says
   LTSPROCKS ;) - this connection is used to open the user session
   and trigger LTSPFS mounts (socket naming is strict)

* LDM then runs the X* xsession rc.d scripts, of which
   X95-run-x-session starts the user's session over a ssh tunnel
   using the same control socket opened earlier

* run function 'start_sound' ->
 - enable access (ACL) to sound device to *pulse* user
 - run service *pulseaudio*

* /etc/X11/Xsession.d/40-ltsp-client - set DESKTOP_SESSION variable

* /usr/share/ldm/rc.d/* - set LOCALA_PPS, REMOTE_APPS, ENV...

#### Shutdown/restart client - upstart (/etc/init/ltsp-client-core.conf)

* run '/usr/share/ltsp/nbd-disconnect' - disconnect NBD image

**Comment by imincik** [comment]
My notes:
* copying debs from server to client and back on client image build makes sense only if arch equals (we will add support for AMD64 in next ticket)
* possible not needed services on client: zeitgeist

**Comment by imincik** [comment]
We need to compare list of packages installed on client before and after we used our own client build system:
* https://gist.github.com/anonymous/c5b937ca9159386a612a  - list of packages installed with our own system

**Comment by imincik** [comment]
Merged to master !
